### ISSUE TITLE
Implementing Future, Stream, Sink yourself

### ISSUE THREAD

**Issue by emschwartz** [tokio-rs/doc-blitz#18]
When building a library that uses Tokio, it seems very common to implement custom Futures, Streams, and Sink types (rather than just using built-in combinators). Coming from other languages I think people might expect to just chain functions, but that doesn't always seems to work with Tokio (though I can't quite put my finger on why). It may be worth having a guide specifically on implementing custom types

**Comment by carllerche** [comment]
I added "how to implement" in the outlines for each trait [here](https://github.com/tokio-rs/doc-blitz/issues/6).

I do agree that calling this out is important and trying to explain why / when to reach for implementing `Future` yourself is needed.

The outline currently has "TODO: Good rule of thumb for when to reach for this", I think the questions you raised apply.

I'm not quite sure what the rule of thumb would be yet.

**Comment by emschwartz** [comment]
Ah right, missed that. I'll comment on that issue
