### ISSUE TITLE
Getting started: should 'Futures' come before 'Runtime Model'?

### ISSUE THREAD

**Issue by nrc** [tokio-rs/doc-blitz#82]
Its not clear to me which of these chapters should come first. Although it's kind of important to understand the polling model before covering futures in depth, the main example in teh runtime model chapter implements a future and it was pretty hard for me to understand that without the explanations in the next chapter.

**Comment by rylev** [comment]
@nrc Now that futures comes before runtime in the new redone getting-started section, should we close this issue?
