### ISSUE TITLE
Additional emphasis on boxed futures and Send

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/doc-blitz#87]
There is a new "returning futures" section here: https://tokio.rs/docs/futures/combinators/#returning-futures

The `Send` issue with boxed futures causes confusion. See #670. The docs should call this hazard out.

**Comment by jeff-hiner** [comment]
https://github.com/tokio-rs/website/pull/247

**Comment by carllerche** [comment]
Thanks for doing this ❤️
