### ISSUE TITLE
Improve example on implementing stream with combinators

### ISSUE THREAD

**Issue by sivakov512** [tokio-rs/doc-blitz#96]
Hi!

[Streams page](https://tokio.rs/docs/futures/streams/#) has an example of implementing Fibonacci stream asynchronously by waiting for one second between values ("Getting asynchronous" section), but section "Combinators" has no example of implementing stream with similar wait.

I learn Tokio and am confused about how to implement it.
I hope someone will help here with an example and explanation.

**Comment by carllerche** [comment]
Good question! Implementing Fibonacci with combinators would look something like:

```rust
use futures::Stream;
use tokio::timer::Interval;
use std::time::Duration;

struct Fibonacci {
    curr: u64,
    next: u64,
}

let mut fib = Fibonacci { curr: 1, next: 1 };

Interval::new_interval(Duration::from_secs(1))
    .map(move |_| {
        let curr = fib.curr;
        let next = curr + fib.next;

        fib.curr = fib.next;
        fib.next = next;

        curr
    })
```

Would you be able to submit a PR to the website adding a fibonnacci section to the combinator page? It doesn't have to be perfect, just get the ball rolling :)

**Comment by sivakov512** [comment]
Thank you! Okay, I will try :)

Also I'm interested in how to implement asynchronous Fibonacci stream through combinator?
I am about this example
```rust

fn fibonacci() -> impl Stream<Item = u64, Error = ()> {
    stream::unfold((1, 1), |(curr, next)| {
        let new_next = curr + next;

        Some(Ok((curr, (next, new_next))))
    })
}
```
Can I extend this function or "chain" with interval stream to get the same result?

**Comment by sivakov512** [comment]
Nothing here?
